In [1]:
import numpy as np

***broadcasting***

In [2]:
var1 = np.array([1,2,3])
var2 = np.array ([[1],[2],[3]])
x= print(np.add(var1,var2))
x

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [3]:
x = np.array([[2],[4],[4],[1]])
print(x.shape)
y = np.array([[2,3,4,4,3]])
print(y.shape)

print(x+y)

(4, 1)
(1, 5)
[[4 5 6 6 5]
 [6 7 8 8 7]
 [6 7 8 8 7]
 [3 4 5 5 4]]


***indexing***

In [4]:
dim1 = np.array([1,2,5])
print("dimention",dim1.ndim)

print(dim1[2])

dimention 1
5


In [5]:
dim2 = np.array([[1,2,3],[4,5,6]])
print("dimention",dim2.ndim)

print(dim2[1,1])

dimention 2
5


In [6]:
dim2 = np.array([[[1,2,3],[4,5,6]],[[4,6,6],[7,8,9]]])
print("dimention",dim2.ndim)

print(dim2[0,1,1])

dimention 3
5


***Slicing***

In [7]:
slice = np.array([1,2,3,4,5,6])
print(slice[4:5])
print(slice[-2:-1])
print(slice[::2])


[5]
[5]
[1 3 5]


In [8]:
slice2 = np.array([[[1,2,3],[4,5,6]],[[4,6,6],[7,8,9]]])

print(slice2[0,1,1:])


[5 6]


***iteration***

In [9]:
var = np.array([1,2,3,4,5])
print(var)
for i in var:
    print(i , end = "")

[1 2 3 4 5]
12345

In [10]:
var = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(var)
print("dimention" ,var.ndim)

for i in var:
    for j in i:
        print(j,end = " ")

print()
print()

var = np.array([[[1,2,3,4,5],[1,2,3,4,5]]])
print(var)
print("dimention" ,var.ndim)

for i in var:
    for j in i:
        for k in j:
            print(k,end = " ")


[[1 2 3 4 5]
 [1 2 3 4 5]]
dimention 2
1 2 3 4 5 1 2 3 4 5 

[[[1 2 3 4 5]
  [1 2 3 4 5]]]
dimention 3
1 2 3 4 5 1 2 3 4 5 

In [11]:
var = np.array([[[1,2,3,4,5],[1,2,3,4,5]]])
for i in np.nditer(var):
    print(i, end = " ")

print()

for i,d in np.ndenumerate(var):
    print(d,i)

1 2 3 4 5 1 2 3 4 5 
1 (0, 0, 0)
2 (0, 0, 1)
3 (0, 0, 2)
4 (0, 0, 3)
5 (0, 0, 4)
1 (0, 1, 0)
2 (0, 1, 1)
3 (0, 1, 2)
4 (0, 1, 3)
5 (0, 1, 4)


***Copy vs View***

In [12]:
var = np.array([1,2,3,4,5])
cpy = var.copy()
cpy[1] = 5
print(f"original {var}")
print("copy",cpy)

print("copy does not affect main data")

vw = var.view()
vw[1]=5
print(f"original {var}")
print("view", vw)

original [1 2 3 4 5]
copy [1 5 3 4 5]
copy does not affect main data
original [1 5 3 4 5]
view [1 5 3 4 5]


***Join***

In [13]:
var = np.array([1,2,3,4,5])
var1 = np.array([6,7,8,9,10])

print(np.concat((var,var1)))

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
var = np.array([[1,2,3],[4,5,6]])
var1 = np.array([[6,7,8],[9,10,11]])

x = np.concatenate((var,var1),axis = 0)
y = np.concatenate((var,var1),axis = 1)

print("x",x ,end ="\n"*3)

print("y",y)

x [[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]


y [[ 1  2  3  6  7  8]
 [ 4  5  6  9 10 11]]


In [15]:
var = np.array([[1,2,3],[4,5,6]])
var1 = np.array([[6,7,8],[9,10,11]])

x = np.stack((var,var1),axis = 0)
y = np.stack((var,var1),axis = 1)
a = np.hstack((var,var1))# xs =0(col)
b = np.vstack((var,var1))# xs =1 (row)
c = np.dstack((var,var1))# height


print("x",x ,end ="\n"*3)
print("a",a ,end ="\n"*3)

print("b",b ,end ="\n"*3)
print("y",y,end ="\n"*3)

print("c",c)


x [[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]


a [[ 1  2  3  6  7  8]
 [ 4  5  6  9 10 11]]


b [[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]


y [[[ 1  2  3]
  [ 6  7  8]]

 [[ 4  5  6]
  [ 9 10 11]]]


c [[[ 1  6]
  [ 2  7]
  [ 3  8]]

 [[ 4  9]
  [ 5 10]
  [ 6 11]]]


***Split***

In [16]:
var = np.array([[1,2,3,4],[4,5,6,5]])
var2 = np.array([1,2,3,4])

splt = np.split(var2,2)
print(splt)
splt2 = np.split(var,2)
print(splt2)

[array([1, 2]), array([3, 4])]
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 5]])]


In [17]:
var = np.array([[1,2,3,4],[4,5,6,5]])


splt = np.split(var,2,axis=0)
print("var2",splt)
splt2 = np.split(var,2, axis = 1)
print("var",splt2)


var2 [array([[1, 2, 3, 4]]), array([[4, 5, 6, 5]])]
var [array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 5]])]


***array functions***

In [18]:
ar = np.array([1,5,3,5,5,6,5,8,9,5])

x = np.where(ar == 5)
print(x)

y = np.where (ar%2!=0)
print(y)

(array([1, 3, 4, 6, 9]),)
(array([0, 1, 2, 3, 4, 6, 8, 9]),)


In [34]:
ar = np.array([1,5,3,5,5,6,5,8,9,5,6])

y = np.searchsorted(ar,11,side='Left')
print(y)

11


In [20]:
ar = np.array([[1,5,3],[55,65,6],[35,8,15]])

print(np.sort(ar))

ar1 = np.array(["a","d","c","b"])

print(np.sort(ar1))



[[ 1  3  5]
 [ 6 55 65]
 [ 8 15 35]]
['a' 'b' 'c' 'd']


In [21]:
arr_1 = np.array(["a","d","c","b"])

fltr = [True,False,True,False]

filtered = arr_1[fltr]
filtered

array(['a', 'c'], dtype='<U1')

In [42]:
ar = np.array([1,5,3,5,5,6,5,8,9,5])
np.random.shuffle(ar)
print(ar)

print(np.unique(ar,return_index=True,return_counts=True))

y = np.resize(ar,(2,5))
print(y)

print(y.flatten("c"))

print(y.flatten("f"))

[8 3 5 5 5 1 5 9 6 5]
(array([1, 3, 5, 6, 8, 9]), array([5, 1, 2, 8, 0, 7]), array([1, 1, 5, 1, 1, 1]))
[[8 3 5 5 5]
 [1 5 9 6 5]]
[8 3 5 5 5 1 5 9 6 5]
[8 1 3 5 5 9 5 6 5 5]


***insertion & Deletion***

In [43]:
ar = np.array([1,5,3,5,5,6,5,8,9,5])

x = np.insert(ar,(1),8.9)
print(x)
y = np.append(ar,6.5)
y

[1 8 5 3 5 5 6 5 8 9 5]


array([1. , 5. , 3. , 5. , 5. , 6. , 5. , 8. , 9. , 5. , 6.5])

In [44]:
ar = np.array([[1,5,3,5],[5,6,5,8]])
v1 = np.insert(ar,4,[8,16],axis=1)
print(v1)

[[ 1  5  3  5  8]
 [ 5  6  5  8 16]]


In [45]:
ar = np.array([1,5,3,5])

dlt = np.delete(ar,1)
print(dlt)

[1 3 5]


***Matrix***

In [26]:
mat = np.matrix([[1,2,3],[4,5,6]])
print(f"{mat} type = {type(mat)}")

arr = np.array([[1,2,3],[4,5,6]])
print(f"{arr} type = {type(arr)}")



[[1 2 3]
 [4 5 6]] type = <class 'numpy.matrix'>
[[1 2 3]
 [4 5 6]] type = <class 'numpy.ndarray'>


In [27]:
var1 = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])

print(var1*var2)
print(var1.dot(var2))

[[3 6]
 [3 6]]
[[3 6]
 [3 6]]


In [46]:
trns = np.matrix([[1,2,3],[6,7,8]])
print(np.transpose(trns))
print(trns.T)
print(np.swapaxes(trns,1,0))

[[1 6]
 [2 7]
 [3 8]]
[[1 6]
 [2 7]
 [3 8]]
[[1 6]
 [2 7]
 [3 8]]


In [29]:
var3 = np.matrix([[1,2],[3,4]])

invrs = np.linalg.inv(var3)
invrs

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [30]:
var4 = np.matrix([[1,2],[3,4]])

print(np.linalg.matrix_power(var4,2))
print(np.linalg.matrix_power(var4,0))
print(np.linalg.matrix_power(var4,-1))

[[ 7 10]
 [15 22]]
[[1 0]
 [0 1]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [31]:
var5 = np.matrix([[1,2,3],[3,4,5],[1,2,3]])
print(np.linalg.det(var5))

0.0
