***ARRAY***

In [2]:
import numpy as np

In [3]:

x = np.array([1,2,3,4])
print(x)
type(x)

[1 2 3 4]


numpy.ndarray

In [4]:
x = [1,2,3,4,5]
np.array(x)


array([1, 2, 3, 4, 5])

In [5]:
y = [1,2,3,4]
print(y)
type(y)

[1, 2, 3, 4]


list

In [6]:
lst = []
while True:
    num = input("add number to the list : ")
    if num == "q" or num == "Q":
        break
    else:
        lst.append(num)
print(np.array(lst))

['3' '3']


***Dimention***

In [7]:
arr1 = np.array ([1,2,3])

print(f"{arr1} \ntype = {type(arr1)} \ndimention of array is {arr1.ndim}")


[1 2 3] 
type = <class 'numpy.ndarray'> 
dimention of array is 1


In [8]:
arr2 = np.array ([[4,5,6],[7,8,9]])
print(f"{arr2} \n type = {type(arr2)} \n dimention of array is {arr2.ndim}")


[[4 5 6]
 [7 8 9]] 
 type = <class 'numpy.ndarray'> 
 dimention of array is 2


In [9]:
arr3 = np.array ([[[1,3,2],[4,5,6],[7,9,8]]])
print(f"{arr3} \n type = {type(arr3)} \n dimention = {np.ndim(arr3)}")


[[[1 3 2]
  [4 5 6]
  [7 9 8]]] 
 type = <class 'numpy.ndarray'> 
 dimention = 3


In [10]:
arrn = np.array([1,2,3],ndmin=10)
print(f"{arrn} \n type = {type(arrn)} \n dimention = {np.ndim(arrn)}")


[[[[[[[[[[1 2 3]]]]]]]]]] 
 type = <class 'numpy.ndarray'> 
 dimention = 10


***Numpy Functions***

In [11]:
zero = np.zeros((5))
print(zero)


zero1 = np.zeros((3,4,5))# 3 dimention, 4 row , 5 columns
zero1

[0. 0. 0. 0. 0.]


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [12]:
one = np.ones(5) 
print(one)

[1. 1. 1. 1. 1.]


In [13]:
empty1 = np.empty(5)
empty1

array([1., 1., 1., 1., 1.])

In [14]:
one1 = np.ones((3,3))
print(one1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
empty2 = np.empty((3,3))
print(empty2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
arange1 = np.arange(6)
print (arange1)
arange2 = np.arange(0,11,2)
print (arange2)

[0 1 2 3 4 5]
[ 0  2  4  6  8 10]


In [17]:
ten = np.full(5,10)
ten

array([10, 10, 10, 10, 10])

In [18]:
eye1 = np.eye(3)
print(eye1)

eye2 = np.eye(4,5)
eye2

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [37]:
identity = np.identity(5)*5 
identity

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [19]:
ln_space = np.linspace(1,10,4)
ln_space

array([ 1.,  4.,  7., 10.])

In [20]:

rdm1 = np.random.rand(5) #(0-1 one included)
print(rdm1)

rdm2 = np.random.randn(5) #(0-1 positive and nagetive)
print(rdm2)

rdm3 = np.random.ranf(5) #(0-.9 one exluded)
print(rdm3)

rdm4 = np.random.randint(1,10,5) #(min , max , total number of value)
print(rdm4)

rdm5 = np.random.randint(10) # randomly genarating from 0-10
print(rdm5)

[0.22145016 0.9013964  0.89249432 0.31252446 0.44808811]
[ 0.27548323  1.23466758 -1.18599595 -0.20464279 -0.59502399]
[0.61982794 0.93363709 0.19939836 0.60740122 0.67145533]
[9 2 4 5 3]
1


***data type***

In [21]:
var = np.array([1,2,3],dtype="int16")
print("data type : ", var.dtype)

var1 = np.array(["ab","cd","ef"])
print("data type : ", var1.dtype)

var2 = np.array([[1,2,3] ,["ab","cd","ef"]],dtype="U1")
print("data type : ", var2.dtype)


data type :  int16
data type :  <U2
data type :  <U1


***type-conversion***

In [22]:
var = np.array([1,2,3,],dtype=np.int8)
print("data type : ",var,"type : ", var.dtype)

var1 = np.array([1,2,3,],dtype=np.str_)
print("data type : ",var1,"type : ", var1.dtype)

data type :  [1 2 3] type :  int8
data type :  ['1' '2' '3'] type :  <U1


In [23]:
var = np.array([1,2,3,],dtype="f")
print(f"data = {var} \ndata type : {var.dtype}")

data = [1. 2. 3.] 
data type : float32


In [24]:
var2 = np.array([1,2,3,],dtype="f")
print(var2.dtype)

update = var2.astype(np.int16)

print(update.dtype)

float32
int16


***Arithmetic operation***

In [25]:
var1 = np.array([1,2,3,4])
addition = var1 + 5
print (addition)

mul = np.multiply(var1,6)
print (mul)


[6 7 8 9]
[ 6 12 18 24]


In [26]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
add = var1 + var2
print("add " ,add)


var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
subtraction = var2 - var1
print("sub ", subtraction)

var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
mul = var1 * var2
print("mul ", mul)

var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
div = var1 / var2
print ("div ",div)

var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
mod = var2 % var1
print ("mod ", mod)

add  [ 6  8 10 12]
sub  [4 4 4 4]
mul  [ 5 12 21 32]
div  [0.2        0.33333333 0.42857143 0.5       ]
mod  [0 0 1 0]


***2d Array***


In [27]:
var1 = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
var2 = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
add = var1+var2
add

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [28]:
var1 = np.array ([[1,2,3,4,5],[6,7,8,9,10]])
var2 = np.array ([[1,2,3,4,5],[6,7,8,9,10]])

square = np.square(var1)
square

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

***Arithmetic Function***

In [29]:
x = np.array([1,2,3,4,5,6,7,8,9])
minimum = np.min(x)
print("min ", minimum)

maximum = np.max(x)
print("max ",maximum)

minimum_arg = np.argmin(x)
print("position of min value ",minimum_arg)

maximum_arg = np.argmax(x)
print("position of max value ",maximum_arg)
  
y = np.array([2,4,8])  
sqroot = np.sqrt(y)
print("square root ",sqroot)

sin = np.sin(y)
print("sin ",sin)


cos = np.cos(y)
print("cos ",cos)


cumsum = np.cumsum(y)
print("cumsum ",cumsum)



min  1
max  9
position of min value  0
position of max value  8
square root  [1.41421356 2.         2.82842712]
sin  [ 0.90929743 -0.7568025   0.98935825]
cos  [-0.41614684 -0.65364362 -0.14550003]
cumsum  [ 2  6 14]


In [30]:
var1 = np.array ([[1,8,10,4,5],[9,2,8,1,4]])

print(np.min(var1,axis=1))
print(np.max(var1,axis=0))

[1 1]
[ 9  8 10  4  5]


***Shape & Reshape***

In [31]:
x = np.array([[1,2,3,4],[1,2,3,4]])

print("shape ",x.shape)
print("dimention ",x.ndim)
print("size ",x.size)


shape  (2, 4)
dimention  2
size  8


In [32]:
ar = np.array([1,2,3,4], ndmin=3 )
print(ar)
print("shape ",ar.shape)
print("dimention ",ar.ndim)
print("size ",ar.size)

[[[1 2 3 4]]]
shape  (1, 1, 4)
dimention  3
size  4


In [33]:
ar1 = np.array([1,2,3,4,5,6])

x = ar1.reshape(3,2)


print(x)
print("dimention:",x.ndim)

[[1 2]
 [3 4]
 [5 6]]
dimention: 2


In [34]:
ar2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

y = ar2.reshape(3,2,2)
print (y )
print ("dimention",y.ndim)
print ("size",y.size)

z= y.reshape(-1)
print (z)
print ("dimention",z.ndim)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
dimention 3
size 12
[ 1  2  3  4  5  6  7  8  9 10 11 12]
dimention 1


***Competition***

In [35]:
%timeit [i**2 for i in range(1,11)] 

622 ns ± 29.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [36]:
%timeit np.arange(1,11)**2

1.26 μs ± 50 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
