In [ ]:
import numpy as np

In [33]:
try :
    mat_a = []
    mat_b = []
    for i in range(4):
        a = int(input("enter matrix a : "))
        b = int(input("enter b : "))
        mat_a.append(a)
        mat_b.append(b)

    matrix_a = np.array(mat_a)
    matrix_b = np.array(mat_b)
    matrix_a = matrix_a.reshape(2,2)
    matrix_b = matrix_b.reshape(2,2)
except ValueError as e:
    print("inter number pls")   

else :
    print(f"you entered : \na :\n{matrix_a} \n b :\n{matrix_b}")



estimator = str(input("which kind of calculation u wanna do (+,-,*,/,T) : "))

if estimator == "+" :
    add =np.add(matrix_a,matrix_b)
    print("\nresult : \n",add)

if estimator == "-" :
    sub =np.subtract(matrix_a,matrix_b)
    print("\nresult : \n",sub)

if estimator == "*" :
    mul =np.multiply(matrix_a,matrix_b)
    print("\nresult : \n",mul)

if estimator == "/" :
    div =np.divide(matrix_a,matrix_b)
    print("\nresult : \n",div)

if estimator.upper() == "T" :
    print("\nresult : \n",matrix_a.T)
    print("\nresult : \n",matrix_b.T)

you entered : 
a :
[[1 1]
 [1 1]] 
 b :
[[1 1]
 [1 1]]

result : 
 [[1 1]
 [1 1]]

result : 
 [[1 1]
 [1 1]]
