**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [2]:
# Please consult the lectures
# ans.
# A vector is 1 dimensional but matrix is 2 dimensional.

**2. How to import `NumPy` library?** 

In [3]:
# To avoid overwriting the output, please code here 

import numpy as np


**3. Convert the given Python list into NumPy array and check its data type**

In [4]:
list_1 = [1,2,3,4,5]


In [5]:
# To avoid overwriting the output, please code here 

array_1 = np.array(list_1)
array_1.dtype


dtype('int64')

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [6]:
# To avoid overwriting the output, please code here 

array = np.arange(6) 
array


array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [7]:
# To avoid overwriting the output, please code here 

array_of_zeros = np.zeros(5) 
array_of_zeros

array([0., 0., 0., 0., 0.])

**6. Generate the following `matrix`.**

In [8]:
# To avoid overwriting the output, please code here 

matrix = np.zeros((3, 4)) 
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [9]:
# To avoid overwriting the output, please code here 

array_of_ones = np.ones(5) 
array_of_ones


array([1., 1., 1., 1., 1.])

**8. Generate an array of "5" tens.**

In [10]:
# To avoid overwriting the output, please code here 

array_of_tens = np.full(5, 10) 
array_of_tens


array([10, 10, 10, 10, 10])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [26]:
# To avoid overwriting the output, please code here 

even_numbers = np.arange(50, 101, 2) 
even_numbers


array([ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
        76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [12]:
# To avoid overwriting the output, please code here 

array_10_points = np.linspace(0, 1, 10)
step_size = array_10_points[1] - array_10_points[0]
array_10_points, step_size


(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 np.float64(0.1111111111111111))

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [13]:
# To avoid overwriting the output, please code here 

vector_array = np.arange(25) 
vector_array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
# To avoid overwriting the output, please code here 

matrix = vector_array.reshape(5, 5) 
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
# To avoid overwriting the output, please code here 

vector_array.shape = (5, 5) 
vector_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [19]:
# To avoid overwriting the output, please code here 

vector = np.arange(0.1, 2.6, 0.1) 
matrix = vector.reshape(5, 5) 
matrix

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [20]:
# To avoid overwriting the output, please code here 

vector_array = np.linspace(0, 24, 25, dtype=int) 
matrix = vector_array.reshape(5, 5) 
print(matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


**14. What is the main difference between `linspace()` and `arange()`?**

In [ ]:

# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.


# linspace(): Tells how many numbers to make.

# arange(): Tells how big the jump between numbers is.

**15. How to generate a single random integer number using NumPy built-in function?**

In [22]:
# To avoid overwriting the output, please code here 

random_integer = np.random.randint(0, 100) 
random_integer

9

**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [33]:
# To avoid overwriting the output, please code here 

matrix = np.random.rand(7, 5) 
print(matrix)

[[0.8528783  0.86507079 0.75291512 0.23016689 0.2328996 ]
 [0.43024261 0.39215131 0.10706406 0.31040606 0.30164931]
 [0.65497203 0.92792767 0.85838448 0.64393545 0.26511538]
 [0.82553116 0.20340575 0.24773133 0.62219248 0.88663972]
 [0.64572526 0.29458502 0.50918432 0.8588736  0.60279687]
 [0.98632645 0.45820239 0.77143109 0.83193578 0.02631014]
 [0.53210285 0.10192161 0.68238329 0.90605328 0.23951391]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [24]:
# To avoid overwriting the output, please code here 

In [35]:

matrix = np.identity(5)*5 
matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 